name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: checkout git
      uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build full
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: lukasbenner/texlive:full_${{github.ref_name}}
        build-args: scheme=scheme-full
        
    - name: Build small
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: lukasbenner/texlive:small_${{github.ref_name}}
        build-args: scheme=scheme-small
  
    - name: Build medium
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: lukasbenner/texlive:medium_${{github.ref_name}}
        build-args: scheme=scheme-medium
        
    - name: push README to Dockerhub
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        destination_container_repo: lukasbenner/texlive
        provider: dockerhub
        short_description: 'Minimal docker image for building latex documents 📄'
        readme_file: 'README.md'
